export const BalanceConfig = {
  snake: {
    baseSpeed: 180,
    boostMultiplier: 1.35,
    turnSpeedDeg: 210,
    startingMass: 10,
    startingSegments: 9,
    baseRadius: 9,
    radiusScale: 1.05,
    massPerSegment: 5,
    maxVisualSegments: 72,
    consumeThreshold: 1.0,
    spawnProtectionMs: 2000,
    boostMinMass: 14,
    boostMassPerSecond: 1.8,
  },
  food: {
    targetCount: 340,
    poolSize: 560,
    largeChance: 0.1,
    goldenChance: 0.015,
    tinyChance: 0.1,
  },
  combat: { killFixedBonus: 25 },
  bot: { thinkIntervalMs: 180, perceptionRadius: 360 },
  arena: { radius: 1425 },
  death: { minDrops: 8, maxDrops: 35 },
  leaderboard: { refreshMs: 250 },
  rewards: { baseCoins: 25 },
};
