import * as Phaser from 'phaser';
import { BalanceConfig } from '../config/balance';
import { ARENAS, BOT_NAMES, MODES, SKINS } from '../config/content';
import { FoodOrb, type FoodKind } from '../entities/Food';
import { Snake } from '../entities/Snake';
import { BotBrain } from '../ai/BotBrain';
import { SpatialGrid } from '../systems/SpatialGrid';
import { PlayerInputController } from '../systems/InputController';
import { canConsume, rankByScore } from '../systems/GameRules';
import { calculateRewards, applyMatchProgress, grantXp } from '../services/ProgressionService';
import { saveService } from '../services/SaveService';
import { audioService } from '../services/AudioService';
import { eventBus } from '../services/EventBus';
import type { ArenaConfig, GameModeConfig, MatchResult } from '../types';

export class GameScene extends Phaser.Scene {
  private mode!:GameModeConfig;private arena!:ArenaConfig;private center={x:1500,y:1500};private safeRadius=BalanceConfig.arena.radius;
  private snakes:Snake[]=[];private bots=new Map<string,BotBrain>();private player!:Snake;private inputController!:PlayerInputController;
  private foods:FoodOrb[]=[];private foodGrid=new SpatialGrid<FoodOrb>(180);private snakeGrid=new SpatialGrid<Snake>(220);
  private startTime=0;private elapsedMs=0;private remaining=0;private battlePlacement:number|null=null;private state:'COUNTDOWN'|'PLAYING'|'FINAL_PHASE'|'ENDED'='COUNTDOWN';private leaderboardAt=0;private ended=false;private paused=false;private playerEndScheduled=false;private pauseText?:Phaser.GameObjects.Text;
  private frameAccumulator=0;private safeZoneGraphics?:Phaser.GameObjects.Graphics;private hud!:Record<string,Phaser.GameObjects.Text>;private leaderboardText!:Phaser.GameObjects.Text;private countdownText!:Phaser.GameObjects.Text;private joyBase!:Phaser.GameObjects.Arc;private joyKnob!:Phaser.GameObjects.Arc;private tutorialText?:Phaser.GameObjects.Text;private respawnTimers=new Map<string,number>();
  constructor(){super('GameScene');}
  init():void{this.snakes.length=0;this.bots.clear();this.foods.length=0;this.foodGrid.clear();this.snakeGrid.clear();this.respawnTimers.clear();this.startTime=0;this.elapsedMs=0;this.remaining=0;this.battlePlacement=null;this.state='COUNTDOWN';this.leaderboardAt=0;this.ended=false;this.paused=false;this.playerEndScheduled=false;this.pauseText=undefined;this.tutorialText=undefined;this.safeZoneGraphics=undefined;this.frameAccumulator=0;}
  create():void{
    audioService.bind(this);
    const modeId=this.registry.get('modeId')??'classic',arenaId=this.registry.get('arenaId')??'meadow';this.mode=MODES.find(m=>m.id===modeId)??MODES[0];this.arena=ARENAS.find(a=>a.id===arenaId)??ARENAS[0];this.center={x:this.arena.width/2,y:this.arena.height/2};this.safeRadius=BalanceConfig.arena.radius;
    this.cameras.main.setBackgroundColor(this.arena.backgroundColor);this.cameras.main.setBounds(0,0,this.arena.width,this.arena.height);this.drawArena();if(this.mode.shrinkingArena)this.safeZoneGraphics=this.add.graphics().setDepth(2);this.spawnFood();this.spawnPopulation();this.inputController=new PlayerInputController(this,()=>({x:this.player.x,y:this.player.y}));this.buildHud();this.cameras.main.startFollow(this.player.head,true,0.08,0.08);this.cameras.main.setZoom(1.05);
    this.remaining=this.mode.durationSeconds;this.countdownText=this.add.text(640,335,'3',{fontFamily:'system-ui',fontSize:'92px',fontStyle:'bold',color:'#ffffff',stroke:'#000000',strokeThickness:8}).setOrigin(0.5).setScrollFactor(0).setDepth(300);
    this.time.delayedCall(1000,()=>this.countdownText.setText('2'));this.time.delayedCall(2000,()=>this.countdownText.setText('1'));this.time.delayedCall(3000,()=>{this.countdownText.setText('GO!');this.state='PLAYING';this.startTime=this.time.now;this.elapsedMs=0;audioService.matchStart();this.time.delayedCall(550,()=>this.countdownText.setVisible(false));});
    if(!saveService.get().tutorialComplete){this.tutorialText=this.add.text(640,630,'Drag / WASD to steer • Eat glowing orbs to grow • tap this tip to skip',{fontFamily:'system-ui',fontSize:'17px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#0d1726cc',padding:{x:16,y:9}}).setOrigin(0.5).setScrollFactor(0).setDepth(350).setInteractive({useHandCursor:true});this.tutorialText.on('pointerdown',()=>{this.tutorialText?.destroy();this.tutorialText=undefined;saveService.get().tutorialComplete=true;saveService.save();});}
    this.input.keyboard?.on('keydown-ESC',()=>this.togglePause());
  }
  private drawArena():void{const g=this.add.graphics().setDepth(0);g.fillStyle(this.arena.backgroundColor,1);g.fillRect(0,0,this.arena.width,this.arena.height);g.lineStyle(18,this.arena.boundaryColor,0.38);g.strokeCircle(this.center.x,this.center.y,BalanceConfig.arena.radius);g.lineStyle(3,this.arena.accentColor,0.28);g.strokeCircle(this.center.x,this.center.y,BalanceConfig.arena.radius-38);const quality=saveService.get().settings.graphics;const count=quality==='low'?35:quality==='medium'?70:110;for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,r=Math.sqrt(Math.random())*(BalanceConfig.arena.radius-100),x=this.center.x+Math.cos(a)*r,y=this.center.y+Math.sin(a)*r;g.fillStyle(this.arena.accentColor,this.arena.id==='neon'?0.12:0.08);if(this.arena.decorationStyle==='flowers'){g.fillCircle(x,y,Phaser.Math.Between(2,5));g.fillCircle(x+4,y+2,2);}else if(this.arena.decorationStyle==='stones'){g.fillRoundedRect(x,y,Phaser.Math.Between(8,20),Phaser.Math.Between(5,12),4);}else{g.fillRect(x,y,Phaser.Math.Between(8,22),2);}}}
  private randomPoint(margin=110):{x:number;y:number}{const a=Math.random()*Math.PI*2,r=Math.sqrt(Math.random())*Math.max(20,this.safeRadius-margin);return{x:this.center.x+Math.cos(a)*r,y:this.center.y+Math.sin(a)*r};}
  private randomSafePoint(margin=260,minSnakeDistance=220):{x:number;y:number}{let best=this.randomPoint(margin),bestDistance=-1;for(let attempt=0;attempt<18;attempt++){const p=this.randomPoint(margin);let nearest=Number.POSITIVE_INFINITY;for(const s of this.snakes){if(!s.alive)continue;nearest=Math.min(nearest,Phaser.Math.Distance.Between(p.x,p.y,s.x,s.y));}if(nearest>=minSnakeDistance)return p;if(nearest>bestDistance){best=p;bestDistance=nearest;}}return best;}
  private drawSafeZone():void{if(!this.safeZoneGraphics)return;const g=this.safeZoneGraphics;g.clear();g.lineStyle(8,0xffcf66,0.55);g.strokeCircle(this.center.x,this.center.y,this.safeRadius);g.lineStyle(2,0xffffff,0.22);g.strokeCircle(this.center.x,this.center.y,Math.max(40,this.safeRadius-28));}
  private randomSkin(){return SKINS[Phaser.Math.Between(0,SKINS.length-1)];}
  private spawnPopulation():void{const p=this.randomSafePoint(350,260);const skin=SKINS.find(s=>s.id===saveService.get().equippedSkinId)??SKINS[0];this.player=new Snake(this,{id:'player',displayName:'YOU',isPlayer:true,isBot:false,x:p.x,y:p.y,heading:Math.random()*Math.PI*2,skin});this.snakes.push(this.player);for(let i=0;i<this.mode.maxSnakes-1;i++)this.spawnBot(i);this.snakeGrid.insert(this.player);}
  private spawnBot(index:number,reuse?:Snake):void{const p=this.randomSafePoint(300,220),mass=Phaser.Math.Between(8,32),heading=Math.random()*Math.PI*2;if(reuse){this.bots.delete(reuse.id);reuse.respawn(p.x,p.y,heading,mass);this.bots.set(reuse.id,new BotBrain(reuse,index));this.snakeGrid.insert(reuse);return;}const bot=new Snake(this,{id:`bot-${index}-${Math.floor(this.time.now)}`,displayName:BOT_NAMES[index%BOT_NAMES.length],isPlayer:false,isBot:true,x:p.x,y:p.y,heading,skin:this.randomSkin(),mass});this.snakes.push(bot);this.bots.set(bot.id,new BotBrain(bot,index));this.snakeGrid.insert(bot);}
  private spawnFood():void{for(let i=0;i<BalanceConfig.food.poolSize;i++)this.foods.push(new FoodOrb(this,i));const target=Math.floor(BalanceConfig.food.targetCount*this.mode.foodMultiplier*this.arena.foodDensity);for(let i=0;i<target;i++)this.activateFood(this.foods[i]);}
  private activateFood(f:FoodOrb,kind?:FoodKind,x?:number,y?:number,value?:number):void{this.foodGrid.remove(f);const p=x===undefined?this.randomPoint(55):{x,y:y!};let k=kind;if(!k){const r=Math.random();k=r<BalanceConfig.food.goldenChance?'golden':r<BalanceConfig.food.goldenChance+BalanceConfig.food.largeChance?'large':r<BalanceConfig.food.goldenChance+BalanceConfig.food.largeChance+BalanceConfig.food.tinyChance?'tiny':'normal';}const vals={tiny:1,normal:2,large:5,golden:12,death:value??4};const colors={tiny:0x96ffbd,normal:0x63e0ff,large:0xff8fc7,golden:0xffde56,death:0xffb55d};f.spawn(p.x,p.y!,k, value??vals[k],colors[k]);this.foodGrid.insert(f);}
  private buildHud():void{const style={fontFamily:'system-ui',fontSize:'15px',fontStyle:'bold',color:'#ffffff',stroke:'#000000',strokeThickness:4};this.hud={rank:this.add.text(28,22,'RANK #20',style),score:this.add.text(28,46,'SCORE 0',style),kills:this.add.text(28,70,'KILLS 0',style),mass:this.add.text(28,94,'MASS 10',style),timer:this.add.text(640,26,'3:00',{...style,fontSize:'24px'}).setOrigin(0.5)};Object.values(this.hud).forEach(t=>t.setScrollFactor(0).setDepth(300));this.leaderboardText=this.add.text(1238,24,'',{fontFamily:'monospace',fontSize:'14px',color:'#ffffff',align:'right',stroke:'#000000',strokeThickness:4}).setOrigin(1,0).setScrollFactor(0).setDepth(300);this.joyBase=this.add.circle(112,610,66,0xffffff,0.08).setStrokeStyle(2,0xffffff,0.18).setScrollFactor(0).setDepth(290);this.joyKnob=this.add.circle(112,610,28,0xffffff,0.18).setScrollFactor(0).setDepth(291);const boost=this.add.circle(1165,610,52,0xff7a5c,0.2).setStrokeStyle(3,0xffa18d,0.4).setScrollFactor(0).setDepth(290);this.add.text(1165,610,'BOOST',{fontFamily:'system-ui',fontSize:'14px',fontStyle:'bold',color:'#ffffff'}).setOrigin(0.5).setScrollFactor(0).setDepth(291);boost.setInteractive();const pause=this.add.text(640,64,'Ⅱ',{fontFamily:'system-ui',fontSize:'20px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#15283dcc',padding:{x:9,y:5}}).setOrigin(0.5).setScrollFactor(0).setDepth(310).setInteractive({useHandCursor:true});pause.on('pointerdown',()=>this.togglePause());}
  private togglePause():void{if(this.state==='ENDED')return;this.paused=!this.paused;this.time.paused=this.paused;if(this.paused){audioService.pause();this.pauseText=this.add.text(640,360,'PAUSED\nPress Esc or tap pause to resume',{fontFamily:'system-ui',fontSize:'34px',fontStyle:'bold',align:'center',color:'#ffffff',backgroundColor:'#0d1726e8',padding:{x:32,y:24}}).setOrigin(0.5).setScrollFactor(0).setDepth(500);}else{audioService.resume();this.pauseText?.destroy();this.pauseText=undefined;}}
  update(time:number,delta:number):void{if(this.paused||this.state==='COUNTDOWN'||this.state==='ENDED')return;delta=Math.min(delta,50);if(saveService.get().settings.fpsTarget==='30'){this.frameAccumulator+=delta;if(this.frameAccumulator<32)return;delta=this.frameAccumulator;this.frameAccumulator=0;}this.elapsedMs+=delta;const elapsed=this.elapsedMs/1000;this.remaining=Math.max(0,this.mode.durationSeconds-elapsed);if(this.remaining<=30&&this.state==='PLAYING')this.state='FINAL_PHASE';if(this.mode.shrinkingArena){const t=Phaser.Math.Clamp(elapsed/this.mode.durationSeconds,0,1);this.safeRadius=Phaser.Math.Linear(BalanceConfig.arena.radius,180,t);this.drawSafeZone();}
    this.inputController.update(this.player.heading);if(this.player.alive)this.player.update(delta,this.inputController.state.desiredAngle,this.inputController.state.boosting,this.center,this.safeRadius,saveService.get().settings.controlSensitivity);
    for(const s of this.snakes){if(!s.alive)continue;if(s.isBot){const brain=this.bots.get(s.id)!;brain.think(time,{foods:this.foodGrid.queryRadius(s.x,s.y,BalanceConfig.bot.perceptionRadius),snakes:this.snakeGrid.queryRadius(s.x,s.y,BalanceConfig.bot.perceptionRadius),center:this.center,radius:this.safeRadius});s.update(delta,brain.desiredAngle,brain.boosting,this.center,this.safeRadius);}this.snakeGrid.update(s);this.collectFood(s);}
    this.resolveCombat();this.handleRespawns();for(const f of this.foods)f.animate(time);this.updateCamera();this.updateHud(time);if(this.remaining<=0&&this.mode.id!=='battle')this.endMatch();if(this.mode.id==='battle'&&this.snakes.filter(s=>s.alive).length<=1)this.endMatch();if(!this.player.alive&&!this.ended&&!this.playerEndScheduled){this.playerEndScheduled=true;this.time.delayedCall(700,()=>this.endMatch());}if(this.tutorialText&&elapsed>12){this.tutorialText.setText('Hunt smaller snakes • Avoid larger snakes • Climb the leaderboard');if(elapsed>18){this.tutorialText.destroy();this.tutorialText=undefined;saveService.get().tutorialComplete=true;saveService.save();}}
  }
  private collectFood(s:Snake):void{if(!s.alive)return;const near=this.foodGrid.queryRadius(s.x,s.y,s.radius+18);for(const f of near){if(!f.active)continue;const dx=f.x-s.x,dy=f.y-s.y;if(dx*dx+dy*dy>(s.radius+10)**2)continue;this.foodGrid.remove(f);f.recycle();const mult=s===this.player?this.mode.growthMultiplier:1;const beforeSegments=s.segments.filter(seg=>seg.visible).length;s.addMass(f.value*mult,f.value);s.foodCollected++;eventBus.emit('food-collected',{snakeId:s.id,value:f.value,kind:f.kind});eventBus.emit('mass-changed',{snakeId:s.id,mass:s.mass});if(s===this.player){audioService.pickup(f.value>=5);if(s.segments.filter(seg=>seg.visible).length>beforeSegments)audioService.growth();this.pickupVfx(f.x,f.y,f.value);if(this.tutorialText)this.tutorialText.setText('Good. Grow larger, then hunt weaker snakes.');}this.time.delayedCall(120+Math.random()*260,()=>this.activateFood(f));}}
  private headTouches(attacker:Snake,victim:Snake):boolean{const rr=(attacker.radius+victim.radius)*0.7;if(Phaser.Math.Distance.Squared(attacker.x,attacker.y,victim.x,victim.y)<=rr*rr)return true;const step=Math.max(1,Math.ceil(victim.segments.length/18));for(let i=0;i<victim.segments.length;i+=step){const seg=victim.segments[i];if(!seg.visible)continue;const r=attacker.radius+seg.radius*0.72;if(Phaser.Math.Distance.Squared(attacker.x,attacker.y,seg.x,seg.y)<=r*r)return true;}return false;}
  private resolveCombat():void{for(const a of this.snakes){if(!a.alive||a.spawnProtected)continue;for(const b of this.snakeGrid.queryRadius(a.x,a.y,260)){if(a===b||!b.alive||b.spawnProtected||a.id>b.id)continue;const aHits=this.headTouches(a,b),bHits=this.headTouches(b,a);if(aHits&&canConsume(a.power,b.power)){this.kill(a,b);continue;}if(bHits&&canConsume(b.power,a.power)){this.kill(b,a);continue;}if(aHits&&bHits){a.heading+=0.35;b.heading-=0.35;}}}}
  private kill(attacker:Snake,victim:Snake):void{if(!victim.alive)return;if(victim===this.player&&this.mode.id==='battle')this.battlePlacement=this.snakes.filter(s=>s.alive).length;this.deathVfx(victim.x,victim.y,victim.radius);victim.die();this.snakeGrid.remove(victim);eventBus.emit('snake-died',{victimId:victim.id,attackerId:attacker.id});eventBus.emit('snake-killed',{attackerId:attacker.id,victimId:victim.id});attacker.kills++;attacker.score+=BalanceConfig.combat.killFixedBonus+Math.floor(victim.mass*0.5);attacker.addMass(Math.max(2,victim.mass*0.08),0);const drops=Phaser.Math.Clamp(Math.floor(victim.mass/3),BalanceConfig.death.minDrops,BalanceConfig.death.maxDrops);for(let i=0;i<drops;i++){const f=this.foods.find(x=>!x.active);if(!f)break;const p=victim.path[Math.min(victim.path.length-1,i*3)]??{x:victim.x,y:victim.y};this.activateFood(f,'death',p.x+Phaser.Math.Between(-24,24),p.y+Phaser.Math.Between(-24,24),Math.max(2,Math.floor(victim.mass/drops*0.55)));}if(attacker===this.player||victim===this.player){this.cameras.main.shake(180,0.004);if(victim===this.player)audioService.death();else audioService.kill();if(saveService.get().settings.vibration&&navigator.vibrate)navigator.vibrate(victim===this.player?[40,40,80]:35);}if(this.mode.allowRespawn&&victim.isBot)this.respawnTimers.set(victim.id,this.elapsedMs+1900);}
  private handleRespawns():void{for(const [id,at] of [...this.respawnTimers])if(this.elapsedMs>=at){const old=this.snakes.find(s=>s.id===id);if(old){const index=Math.max(0,BOT_NAMES.indexOf(old.displayName));this.spawnBot(index,old);}this.respawnTimers.delete(id);}}
  private pickupVfx(x:number,y:number,value:number):void{if(saveService.get().settings.graphics==='low')return;const ring=this.add.circle(x,y,8,0xffffff,0).setStrokeStyle(2,value>=5?0xffdf70:0xa7f6ff,0.9).setDepth(20);this.tweens.add({targets:ring,radius:24,alpha:0,duration:250,onComplete:()=>ring.destroy()});}
  private deathVfx(x:number,y:number,radius:number):void{if(saveService.get().settings.graphics==='low')return;const ring=this.add.circle(x,y,radius,0xffffff,0).setStrokeStyle(3,0xffc18a,0.9).setDepth(22);this.tweens.add({targets:ring,radius:radius+48,alpha:0,duration:320,onComplete:()=>ring.destroy()});}
  private updateCamera():void{if(!this.player.alive)return;const target=Phaser.Math.Clamp(1.1-Math.sqrt(this.player.mass)*0.012,0.58,1.04),look=Phaser.Math.Clamp(36+Math.sqrt(this.player.mass)*2.2,36,82);this.cameras.main.setZoom(Phaser.Math.Linear(this.cameras.main.zoom,target,0.035));this.cameras.main.setFollowOffset(-Math.cos(this.player.heading)*look,-Math.sin(this.player.heading)*look);}
  private updateHud(time:number):void{const mins=Math.floor(this.remaining/60),secs=Math.floor(this.remaining%60);this.hud.timer.setText(this.mode.id==='battle'&&this.remaining<=0?'OVERTIME':`${mins}:${secs.toString().padStart(2,'0')}`);if(this.state==='FINAL_PHASE')this.hud.timer.setColor(Math.floor(time/400)%2?'#ffcf66':'#ffffff');this.hud.score.setText(`SCORE ${Math.floor(this.player.score).toLocaleString()}`);this.hud.kills.setText(`KILLS ${this.player.kills}`);this.hud.mass.setText(`MASS ${Math.floor(this.player.mass)}`);this.joyBase.setPosition(this.inputController.joystickOrigin.x,this.inputController.joystickOrigin.y);this.joyKnob.setPosition(this.inputController.joystickOrigin.x+this.inputController.joystickVector.x,this.inputController.joystickOrigin.y+this.inputController.joystickVector.y);if(time>=this.leaderboardAt){this.leaderboardAt=time+BalanceConfig.leaderboard.refreshMs;const ranked=rankByScore(this.snakes);ranked.forEach((s,i)=>s.rank=i+1);for(const s of this.snakes){if(s===this.player||!s.alive)continue;const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,s.x,s.y);if(d<520){s.nameText.setColor(s.power>this.player.power*1.05?'#ffb26b':this.player.power>s.power*1.05?'#86ffab':'#ffffff');}else s.nameText.setColor('#ffffff');}const pr=ranked.indexOf(this.player)+1;this.hud.rank.setText(`RANK #${pr}`);const top=ranked.slice(0,5).map((s,i)=>`${i+1}. ${s===this.player?'YOU':s.displayName.padEnd(7)} ${Math.floor(s.score)}`);if(pr>5)top.push(`…\n${pr}. YOU ${Math.floor(this.player.score)}`);this.leaderboardText.setText(top.join('\n'));}}
  private endMatch():void{if(this.ended)return;this.ended=true;this.state='ENDED';this.time.paused=false;audioService.matchEnd();const ranked=rankByScore(this.snakes);const placement=this.mode.id==='battle'?(this.battlePlacement??1):Math.max(1,ranked.indexOf(this.player)+1);const rewards=calculateRewards(placement,Math.floor(this.player.score),this.player.kills);const survived=this.elapsedMs/1000;const result:MatchResult={modeId:this.mode.id,arenaId:this.arena.id,placement,score:Math.floor(this.player.score),kills:this.player.kills,maxMass:Math.floor(this.player.maxMass),foodCollected:this.player.foodCollected,survivedSeconds:Math.floor(survived),coinsEarned:rewards.coins,xpEarned:rewards.xp,rewardsGranted:false};if(!result.rewardsGranted){result.rewardsGranted=true;const data=saveService.get();data.coins+=result.coinsEarned;const levels=grantXp(data,result.xpEarned);result.levelUps=levels;applyMatchProgress(result);if(levels>0)audioService.levelUp();eventBus.emit('match-ended',result);this.registry.set('lastResult',result);this.time.delayedCall(300,()=>this.scene.start('ResultsScene'));}}
}
