import * as Phaser from 'phaser';
import { ARENAS, DAILY_REWARDS, MISSIONS, MODES, SKINS } from '../config/content';
import { addButton, panel } from '../ui/uiHelpers';
import { claimDaily, claimMission, dailyAvailable, equipSkin, purchaseSkin, xpForNextLevel } from '../services/ProgressionService';
import { saveService } from '../services/SaveService';
import { audioService } from '../services/AudioService';

export class MainMenuScene extends Phaser.Scene {
  private modeIndex=0;private arenaIndex=0;private layer?:Phaser.GameObjects.Container;
  constructor(){super('MainMenuScene');}
  create():void{
    this.layer=undefined;audioService.bind(this);this.cameras.main.setBackgroundColor(0x091522); this.drawBackdrop(); if(this.registry.get('openSkins')){this.registry.set('openSkins',false);this.showSkins(false);}else this.showHome();
  }
  private drawBackdrop():void{ const g=this.add.graphics(); for(let i=0;i<32;i++){const x=Phaser.Math.Between(0,1280),y=Phaser.Math.Between(0,720),r=Phaser.Math.Between(3,11);g.fillStyle([0x44f7ff,0xff4fd8,0x63e07b][i%3],0.08);g.fillCircle(x,y,r);} }
  private clearLayer():void{this.layer?.destroy(true);this.layer=this.add.container(0,0).setDepth(50);}
  private track(obj:Phaser.GameObjects.GameObject):void{this.layer?.add(obj);}
  private heading(title:string,subtitle=''):void{this.track(this.add.text(64,45,title,{fontFamily:'system-ui',fontSize:'42px',fontStyle:'bold',color:'#ffffff'}));if(subtitle)this.track(this.add.text(66,96,subtitle,{fontFamily:'system-ui',fontSize:'16px',color:'#9bb3ca'}));}
  private topStats():void{const d=saveService.get();const xpNeed=xpForNextLevel(d.level);this.track(this.add.text(930,38,`COINS  ${d.coins.toLocaleString()}    LV ${d.level}`,{fontFamily:'system-ui',fontSize:'18px',fontStyle:'bold',color:'#f7d75a'}));const bar=this.add.rectangle(1075,76,220,10,0x1b3049).setOrigin(0);const fill=this.add.rectangle(1075,76,220*Phaser.Math.Clamp(d.xp/xpNeed,0,1),10,0x5ee887).setOrigin(0);this.track(bar);this.track(fill);this.track(this.add.text(1075,90,`${d.xp} / ${xpNeed} XP`,{fontFamily:'system-ui',fontSize:'12px',color:'#9bb3ca'}));}
  private button(x:number,y:number,w:number,h:number,label:string,cb:()=>void,primary=false):void{const b=addButton(this,x,y,w,h,label,()=>{audioService.ui();cb();},primary);this.track(b);}
  private showHome():void{this.clearLayer();this.heading('COIL ARENA','Offline snake-arena combat • grow, hunt, survive');this.topStats();this.track(this.add.text(640,165,'BUILD YOUR COIL. OWN THE ARENA.',{fontFamily:'system-ui',fontSize:'28px',fontStyle:'bold',color:'#dfffea'}).setOrigin(0.5));this.button(640,238,340,68,'PLAY',()=>{this.registry.set('modeId',MODES[this.modeIndex].id);this.registry.set('arenaId',ARENAS[this.arenaIndex].id);this.scene.start('GameScene');},true);
    this.button(465,328,160,46,'‹ MODE',()=>{this.modeIndex=(this.modeIndex+MODES.length-1)%MODES.length;this.showHome();});this.track(this.add.text(640,328,MODES[this.modeIndex].displayName,{fontFamily:'system-ui',fontSize:'19px',fontStyle:'bold',color:'#ffffff'}).setOrigin(0.5));this.button(815,328,160,46,'MODE ›',()=>{this.modeIndex=(this.modeIndex+1)%MODES.length;this.showHome();});
    this.button(465,386,160,46,'‹ ARENA',()=>{this.arenaIndex=(this.arenaIndex+ARENAS.length-1)%ARENAS.length;this.showHome();});this.track(this.add.text(640,386,ARENAS[this.arenaIndex].name,{fontFamily:'system-ui',fontSize:'19px',fontStyle:'bold',color:'#ffffff'}).setOrigin(0.5));this.button(815,386,160,46,'ARENA ›',()=>{this.arenaIndex=(this.arenaIndex+1)%ARENAS.length;this.showHome();});
    const items:[string,()=>void][]=[['SKINS',()=>this.showSkins(false)],['SHOP',()=>this.showSkins(true)],['MISSIONS',()=>this.showMissions()],['DAILY',()=>this.showDaily()],['SETTINGS',()=>this.showSettings()],['STATS',()=>this.showStats()]];items.forEach((it,i)=>this.button(290+(i%3)*350,495+Math.floor(i/3)*72,260,52,it[0],it[1])); }
  private back():void{this.button(112,666,150,42,'BACK',()=>this.showHome());}
  private showSkins(shop:boolean):void{this.clearLayer();this.heading(shop?'SKIN SHOP':'SKINS',shop?'Unlock original cosmetics with earned coins.':'Equip any unlocked skin.');this.topStats();this.track(panel(this,640,390,1120,500));const d=saveService.get();SKINS.forEach((s,i)=>{const col=i%4,row=Math.floor(i/4),x=230+col*275,y=260+row*220;const unlocked=d.unlockedSkinIds.includes(s.id);const card=this.add.rectangle(x,y,235,178,0x172a40,0.96).setStrokeStyle(2,d.equippedSkinId===s.id?0x5ee887:0x395777,0.8);this.track(card);const head=this.add.circle(x,y-42,26,s.headColor);this.track(head);for(let k=0;k<5;k++)this.track(this.add.circle(x-54+k*27,y+1,14,s.bodyColors[k%s.bodyColors.length]));this.track(this.add.text(x,y+35,s.displayName,{fontFamily:'system-ui',fontSize:'16px',fontStyle:'bold',color:'#ffffff'}).setOrigin(0.5));this.track(this.add.text(x,y+58,s.rarity.toUpperCase(),{fontFamily:'system-ui',fontSize:'11px',color:'#9bb3ca'}).setOrigin(0.5));const label=unlocked?(d.equippedSkinId===s.id?'EQUIPPED':'EQUIP'):shop?`${s.unlockCost} COINS`:'LOCKED';this.button(x,y+93,170,34,label,()=>{if(unlocked)equipSkin(s.id);else if(shop)purchaseSkin(s.id);this.showSkins(shop);},unlocked&&d.equippedSkinId!==s.id);});this.back();}
  private showMissions():void{this.clearLayer();this.heading('MISSIONS','Complete goals, then claim coin rewards.');this.topStats();this.track(panel(this,640,385,1120,510));MISSIONS.forEach((m,i)=>{const s=saveService.get().missionState.find(x=>x.id===m.id)!;const x=i%2===0?370:910,y=175+Math.floor(i/2)*113;this.track(this.add.text(x-210,y,m.title,{fontFamily:'system-ui',fontSize:'17px',fontStyle:'bold',color:'#ffffff'}));this.track(this.add.text(x-210,y+28,`${Math.floor(s.progress)} / ${m.target}   •   ${m.reward} coins`,{fontFamily:'system-ui',fontSize:'13px',color:s.complete?'#78ef9a':'#9bb3ca'}));this.button(x+145,y+20,118,38,s.claimed?'CLAIMED':s.complete?'CLAIM':'ACTIVE',()=>{if(s.complete&&!s.claimed)claimMission(m.id);this.showMissions();},s.complete&&!s.claimed);});this.back();}
  private showDaily():void{this.clearLayer();this.heading('DAILY REWARD','A simple seven-day offline reward cycle.');this.topStats();const d=saveService.get();DAILY_REWARDS.forEach((v,i)=>{const x=180+i*153;this.track(this.add.circle(x,300,54,i===d.dailyReward.cycleDay?0x5ee887:0x243a54,0.95));this.track(this.add.text(x,286,`DAY ${i+1}`,{fontFamily:'system-ui',fontSize:'12px',fontStyle:'bold',color:'#ffffff'}).setOrigin(0.5));this.track(this.add.text(x,314,`${v}`,{fontFamily:'system-ui',fontSize:'19px',fontStyle:'bold',color:'#f7d75a'}).setOrigin(0.5));});this.button(640,452,320,58,dailyAvailable()?'CLAIM TODAY':'CLAIMED TODAY',()=>{claimDaily();this.showDaily();},dailyAvailable());this.back();}
  private showSettings():void{this.clearLayer();this.heading('SETTINGS','Changes save immediately.');this.topStats();const d=saveService.get(),s=d.settings;const rows:[string,string,()=>void][]=[['Music volume',`${Math.round(s.musicVolume*100)}%`,()=>{s.musicVolume=s.musicVolume>=1?0:Math.min(1,s.musicVolume+0.25);saveService.save();audioService.syncSettings();this.showSettings();}],['SFX volume',`${Math.round(s.sfxVolume*100)}%`,()=>{s.sfxVolume=s.sfxVolume>=1?0:Math.min(1,s.sfxVolume+0.25);saveService.save();this.showSettings();}],['Vibration',s.vibration?'ON':'OFF',()=>{s.vibration=!s.vibration;saveService.save();this.showSettings();}],['Control style',s.controlStyle.toUpperCase(),()=>{s.controlStyle=s.controlStyle==='drag'?'joystick':'drag';saveService.save();this.showSettings();}],['Sensitivity',s.controlSensitivity.toFixed(1),()=>{s.controlSensitivity=s.controlSensitivity>=1.4?0.8:s.controlSensitivity+0.2;saveService.save();this.showSettings();}],['Graphics',s.graphics.toUpperCase(),()=>{s.graphics=s.graphics==='high'?'low':s.graphics==='low'?'medium':'high';saveService.save();this.showSettings();}],['FPS target',s.fpsTarget.toUpperCase(),()=>{s.fpsTarget=s.fpsTarget==='auto'?'30':s.fpsTarget==='30'?'60':'auto';saveService.save();this.showSettings();}],['Fullscreen',this.scale.isFullscreen?'ON':'OFF',()=>{if(this.scale.isFullscreen)this.scale.stopFullscreen();else this.scale.startFullscreen();this.time.delayedCall(120,()=>this.showSettings());}]];rows.forEach((r,i)=>{const y=152+i*56;this.track(this.add.text(330,y,r[0],{fontFamily:'system-ui',fontSize:'18px',color:'#ffffff'}));this.button(835,y+8,260,42,r[1],r[2]);});this.button(835,610,260,38,'RESET PROGRESS',()=>{if(window.confirm('Reset all Coil Arena progress?')){saveService.reset();audioService.syncSettings();this.showHome();}});this.button(540,610,260,38,'CREDITS',()=>this.showCredits());this.back();}
  private showCredits():void{this.clearLayer();this.heading('CREDITS','Original offline game implementation.');this.topStats();this.track(panel(this,640,360,850,360));this.track(this.add.text(640,270,'COIL ARENA',{fontFamily:'system-ui',fontSize:'34px',fontStyle:'bold',color:'#ffffff'}).setOrigin(0.5));this.track(this.add.text(640,330,'Built with Phaser 4 + TypeScript\nProcedural game art • no copied game assets\nOffline bots and local progression',{fontFamily:'system-ui',fontSize:'17px',align:'center',color:'#b7c9dc',lineSpacing:10}).setOrigin(0.5));this.back();}
  private showStats():void{this.clearLayer();this.heading('LIFETIME STATS');this.topStats();const s=saveService.get().stats;const rows=[['Matches',s.matchesPlayed],['Wins',s.wins],['Top 3',s.top3],['Total score',s.totalScore],['Food collected',s.totalFood],['Kills',s.totalKills],['Highest mass',Math.floor(s.highestMass)],['Best rank',s.bestRank],['Longest survival',`${Math.floor(s.longestSurvival)}s`]];rows.forEach((r,i)=>{const x=i%2===0?390:850,y=170+Math.floor(i/2)*78;this.track(this.add.text(x-130,y,String(r[0]),{fontFamily:'system-ui',fontSize:'17px',color:'#9bb3ca'}));this.track(this.add.text(x+120,y,String(r[1]),{fontFamily:'system-ui',fontSize:'20px',fontStyle:'bold',color:'#ffffff'}).setOrigin(1,0));});this.back();}
}
